name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  dio: ^5.3.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
  mocked_backend: ^1.0.7

flutter:
  uses-material-design: true