name: mocked_backend
description: Mocked backend for testing
version: 1.0.4
repository: https://github.com/RonyBrosh/mocked_backend.git

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


