name: Publish to pub.dev
on: workflow_dispatch
jobs:
  publish_library:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the code
          uses: actions/checkout@v2
        - name: Install Flutter
          uses: subosito/flutter-action@v1
          with:
            channel: 'stable'
        - name: Push to pub.dev
          run: dart pub publish && echo y
